using LibraryManagementSystem.Application.Common.Models;
using LibraryManagementSystem.Application.Features.BookReservation.DTOs;
using MediatR;

namespace LibraryManagementSystem.Application.Features.BookReservation.Commands;

public record NotifyNextReservationUserCommand(NotifyNextReservationUserRequestDto notifyNextReservationUserRequestDto)
    : IRequest<ApiResponseModel<NotifyNextReservationUserResponseDto>>;